# Generated by Django 2.1.3 on 2018-12-10 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agricultor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_agricultor', models.CharField(max_length=250)),
                ('qtd_credito', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_parcela', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_emprestimo', models.IntegerField()),
                ('juros', models.IntegerField()),
                ('qtd_parcela', models.IntegerField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimo', to='appfinanceiro.Banco')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCultura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cultura', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='agricultor',
            name='emprestimo',
            field=models.ManyToManyField(related_name='agricultor', to='appfinanceiro.Emprestimo'),
        ),
        migrations.AddField(
            model_name='agricultor',
            name='tipo_cultura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agricultor', to='appfinanceiro.TipoCultura'),
        ),
    ]
