# Generated by Django 2.1.3 on 2018-12-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinanceiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agricultor',
            name='qtd_credito',
            field=models.IntegerField(default=0),
        ),
    ]
