# Generated by Django 2.1.3 on 2018-12-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinanceiro', '0002_auto_20181210_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agricultor',
            name='qtd_credito',
            field=models.PositiveIntegerField(),
        ),
    ]
