# Generated by Django 2.1.3 on 2018-12-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinanceiro', '0003_auto_20181210_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='juros',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='qtd_emprestimo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='qtd_parcela',
            field=models.PositiveIntegerField(),
        ),
    ]
