# Generated by Django 2.1.3 on 2018-12-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinanceiro', '0004_auto_20181210_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='dt_emprestimo',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
