# Generated by Django 2.1.3 on 2018-12-11 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinanceiro', '0005_emprestimo_dt_emprestimo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banco',
            old_name='qtd_parcela',
            new_name='nome_banco',
        ),
    ]
