# Generated by Django 2.1.3 on 2018-12-11 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appfinanceiro', '0006_auto_20181210_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agricultor',
            name='emprestimo',
            field=models.ManyToManyField(default='sem emprestimo', related_name='agricultor', to='appfinanceiro.Emprestimo'),
        ),
        migrations.AlterField(
            model_name='agricultor',
            name='tipo_cultura',
            field=models.ForeignKey(default='sem plantação', on_delete=django.db.models.deletion.CASCADE, related_name='agricultor', to='appfinanceiro.TipoCultura'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='banco',
            field=models.ForeignKey(default='sem banco', on_delete=django.db.models.deletion.CASCADE, related_name='emprestimo', to='appfinanceiro.Banco'),
        ),
    ]
