# Generated by Django 2.1.3 on 2018-11-17 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='solicitacoes',
        ),
    ]
